config/routes.rb
Hackplay::Application.routes.draw do

  root to: "games#index"

  resources :games  do
    resources :votes, :only => [:create]
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :name, :description, :equipment, :video_url
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :game_id
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
    # @games = Game.order("created_at DESC")
    # @games = Game.all.sort_by(&:votes)
  end

  def new
    @game = Game.new
  end

  def show
    @game = Game.find(params['id'])
    @vote = Vote.new
  end

  def create
    Game.create(params['game'])
    redirect_to :root
  end

  # def edit
  # end

  # def update
  # end

  # def destroy
  # end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    id = params['game_id'].to_i
    Vote.create(game_id: id)
    game = Game.find(id)
    redirect_to :back
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<div class="top-section">

  <img id="logo" src="<%=asset_path 'logo_sm.png'%>" width="100px" alt="logo">

  <button class='big-button'><%= link_to "Share your game!", new_game_path %></button>
  <h4><i>Share a game or play one listed below!</i></h4>
</div>

<div class="spacer"></div>

<div class="sort-buttons">
  <span class="description">Sort by:</span>
  <%= link_to "Most Liked", :root, class:'subdued-button' %>
  <%= link_to "Newest", :root, class:'subdued-button' %>
  <%= link_to "Outdoor Games", :root, class:'subdued-button' %>
  <%= link_to "Indoor Games", :root, class:'subdued-button' %>
  <%= link_to "Ages: 2+", :root, class:'subdued-button' %>
  <%= link_to "Ages: 5+", :root, class:'subdued-button' %>
  <%= link_to "Ages: 10+", :root, class:'subdued-button' %>
  <%= link_to "Ages: 18+", :root, class:'subdued-button' %>
</div>

<% @games.each do |game| %>
  <div class="game-description">
    <h2><%= game.name %>  <span class="likes">likes: <%= game.votes.count %></span></h2>
    <br>
    <%= link_to "Read how to play!", game_path(game), class:'regular-button' %>
  </div>
<% end %>

app/views/games/new.html.erb
<div class="game-create">
  <h2>Tell us about your game!</h2><br>

  <%= form_for @game, url: {action: "create"} do |f|  %>
    <%= f.label :name, "What's this game called?" %><br>
    <%= f.text_field :name %> <br>

    <%= f.label :description, "How do you play?" %><br>
    <%= f.text_area :description  %> <br>

    <%= f.label :equipment, "What gear do you need?"%><br>
    <%= f.text_field :equipment  %> <br>

  <%= f.label :video_url, "Share link to a short Vine or YouTube of you playing this game"%><br>
  <%= f.text_field :video_url  %> <br>

    <%= f.submit "Share this game!", class: "big-button" %>
  <% end %>

  <%= link_to "Cancel", :root, class:'regular-button' %>
</div>

app/views/games/show.html.erb
<div class="game-full-description">
  <h2><%= @game.name %> </h2><br>

  <!-- AddThis Button BEGIN -->
  <div class="addthis_toolbox addthis_default_style ">
    <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
    <a class="addthis_button_tweet"></a>
    <a class="addthis_button_pinterest_pinit"></a>
    <a class="addthis_counter addthis_pill_style"></a>
  </div>
  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-5210c6694764912d"></script>
  <!-- AddThis Button END -->

  <h3>Description:</h3> <p> <%= @game.description %> </p>
  <h3>Equipment:</h3> <p> <%= @game.equipment %> </p>
  <h3>Likes:</h3> <p> <%= @game.votes.count %>

    <%= form_for @vote, url: game_votes_path(@game) do |f|  %>
      <%= f.submit "Like", class: "big-button" %>
    <% end %>



  <%= link_to "Back to big list", :root, class:'regular-button' %>
</div>


<iframe title="YouTube video player" class="youtube-player" type="text/html"
width="640" height="390" src="<%= @game.video_url %>"
frameborder="0" allowFullScreen></iframe>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackplay</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- Selected Google fonts: -->
  <link href='http://fonts.googleapis.com/css?family=Fauna+One' rel='stylesheet' type='text/css'
  media="screen and (min-width: 40.5em)">
  <link href='http://fonts.googleapis.com/css?family=Finger+Paint' rel='stylesheet' type='text/css'>

</head>
<body>

<%= yield %>

</body>
</html>